---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgo
spec:
  template:
    spec:
      containers:
      - name: operator
        env:
        - name: PGO_TARGET_NAMESPACE
          valueFrom: { fieldRef: { apiVersion: v1, fieldPath: metadata.namespace } }
        resources:
          requests:
            cpu: 100m
            memory:  256Mi
            ephemeral-storage: 512Mi
          limits:
            cpu: 250m
            memory:  256Mi
            ephemeral-storage: 512Mi

